name: Hotel Price Monitor

on:
  schedule:
    - cron: "0 12 * * 1-5"
    - cron: "0 23 * * 5"
    - cron: "0 23 * * 6"
    - cron: "0 11 * * 6"
    - cron: "0 11 * * 0"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: hotel-price-monitor

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies manually
        run: |
          pip install requests
          pip install beautifulsoup4

      - name: Run hotel price monitor
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          RAKUTEN_URL: ${{ secrets.RAKUTEN_URL }}
          JALAN_URL: ${{ secrets.JALAN_URL }}
        run: python hotel.py
